Fix laggy typing effect
httpete-ire/typer pull request #17
Opened 2016-10-15 03:19 UTC by paul-shibanov

# Significant performance improvement (2x-4x)
## Added names for easy debugging
![screenshot from 2016-10-15 05-58-52](https://cloud.githubusercontent.com/assets/5096640/19407023/76618324-92a6-11e6-8136-0b55f09861a7.png)
## Removed model dirty checking
No more costly $apply() every 16ms. It was very painful for large apps 
![screenshot from 2016-10-15 06-01-32](https://cloud.githubusercontent.com/assets/5096640/19407024/7662f894-92a6-11e6-986f-d4e02ea45b43.png)
## jqlite's .html() replaced by textContent
![screenshot from 2016-10-15 06-04-37](https://cloud.githubusercontent.com/assets/5096640/19407059/8a4e2260-92a7-11e6-81e0-59069ac9cf26.png)

Now it is not treated as html (no parse at all)

2016-12-26 12:44 UTC, httpete-ire commented on src/typer.js
> +          element[0].textContent = word.substring(0, index + 1);
the `element` variable is the DOM element, `element[0]` is unnecessary. This will fix the failing test as it tries to call textContent on undefined.

2016-12-26 12:45 UTC, httpete-ire commented on src/typer.js
> +          element[0].textContent = word.substring(0, letters - 1);
same as above

2016-12-26 12:45 UTC, httpete-ire commented on src/typer.js
> +          config.span[0].textContent = word.substring(letters - 1);
same as above

2016-12-26 12:47 UTC, httpete-ire requested changes
Wow thats a great PR, some great performance gains.

I'd be happy to merge the PR if you update it with the changes I suggested. You might also bump the version number so I can release the new version to NPM.

2016-12-27 07:26 UTC, paul-shibanov commented
@httpete-ire 
Great! Please review.

2016-12-27 23:00 UTC, httpete-ire approved these changes
LGTM 👍

2016-12-27 23:01 UTC, merged